// This file was generated by PermissionsDispatcher. Do not modify!
package design.semicolon.modarenta.activities;

import android.support.v4.app.ActivityCompat;
import java.lang.String;

import design.semicolon.modarenta.activities.MapFullScreenActivity;
import permissions.dispatcher.PermissionUtils;

/**
 * Created by rakhe on 3/5/2016.
 */
final class MapFullScreenActivityPermissionDispatcher {

    private static final int REQUEST_GETMYLOCATION = 0;

    private static final String[] PERMISSION_GETMYLOCATION = new String[] {"android.permission.ACCESS_FINE_LOCATION","android.permission.ACCESS_COARSE_LOCATION"};

    private MapFullScreenActivityPermissionDispatcher() {
    }

    static void getMyLocationWithCheck(MapFullScreenActivity target) {
        if (PermissionUtils.hasSelfPermissions(target, PERMISSION_GETMYLOCATION)) {
            target.getMyLocation();
        } else {
            ActivityCompat.requestPermissions(target, PERMISSION_GETMYLOCATION, REQUEST_GETMYLOCATION);
        }
    }

    static void onRequestPermissionsResult(MapFullScreenActivity target, int requestCode, int[] grantResults) {
        switch (requestCode) {
            case REQUEST_GETMYLOCATION:
                if (PermissionUtils.getTargetSdkVersion(target) < 23 && !PermissionUtils.hasSelfPermissions(target, PERMISSION_GETMYLOCATION)) {
                    return;
                }
                if (PermissionUtils.verifyPermissions(grantResults)) {
                    target.getMyLocation();
                }
                break;
            default:
                break;
        }
    }
}

